name: Push new image to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '22'
          distribution: 'temurin'
        
      - name: Build with Maven
        run: |
          cd api/schoolio-api
          mvn -B package --file pom.xml -DskipTests


      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: api/schoolio-api
          file: api/schoolio-api/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/schoolio-app:latest
          build-args: |
            MONGO_DB_CONNECTION_URL=${{ secrets.MONGO_DB_CONNECTION_URL }}
            MONGO_DB_DATABASE_NAME=${{ secrets.MONGO_DB_DATABASE_NAME }}



